
import com.qoppa.pdf.PDFException;
import com.qoppa.pdf.PrintSettings;
import com.qoppa.pdfViewer.PDFViewerBean;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import farmacia.conectar;
import farmacia.remision;
import java.awt.print.PrinterException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NaMYY
 */
public class caja extends javax.swing.JPanel {

    private final JFrame anfitrion;
    private final JFrame actual;
    private PDFViewerBean remision = new PDFViewerBean();
    private double consulta = 0, vacunas = 0;
    
    /**
     * Creates new form caja
     * @param anfitrion
     * @param actual
     */
    public caja(JFrame anfitrion, JFrame actual, int id) {
        this.anfitrion = anfitrion;
        this.actual = actual;
        initComponents();
        try{
            Connection cnn = (new conectar()).conect();
            Statement stmt = cnn.createStatement();
            ResultSet rs = stmt.executeQuery("select nombres, apellidos, curdate() as fecha from vendedor where idVendedor = -1");
            rs.next();
            jLabel4.setText(rs.getString("nombres") + " " + rs.getString("apellidos"));
            jLabel5.setText(rs.getString("fecha"));
            rs = stmt.executeQuery("select * from configuracion");
            rs.next();
            consulta = rs.getDouble("consulta");
            vacunas = rs.getDouble("vacunas");
            rs.close();
            stmt.close();
            cnn.close();
            jTextField1.setText(consulta + "");
        }catch(Exception e){

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Concepto de pago:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "consulta", "medicamentos", "vacunas" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });

        jLabel2.setText("Total:          $");

        jTextField1.setText("1500");

        jButton1.setText("Registrar pago");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Sistema de caja");

        jButton2.setText("Cerrar sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(57, 57, 57)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(132, 132, 132)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String selected = jComboBox1.getSelectedItem().toString();
        Double cantidad;
        boolean pasa = false;
        switch(selected){
            case "consulta":
                pasa = Double.parseDouble(jTextField1.getText()) == (consulta);
                break;
            case "vacunas":
                pasa = Double.parseDouble(jTextField1.getText()) == (vacunas);
                break;
            default:
                pasa = true;
                break;
        }
        if(!pasa){
            JOptionPane.showMessageDialog(this, "Verifica el precio que estas dando");
            switch(selected){
                case "consulta":
                    jTextField1.setText(consulta + "");
                    break;
                case "vacunas":
                    jTextField1.setText(vacunas + "");
                    break;
                case "medicamentos":
                    jTextField1.setText("0");
                    break;
            }
        }else{
            try{
                cantidad = Double.parseDouble(jTextField1.getText());
                Connection cnn = (new conectar()).conect();
                Statement stmt = cnn.createStatement();
                stmt.execute("insert into compras values(default, "+cantidad+",'"+selected+"', concat(curdate(), ' ',curtime()))");
                remision r = new remision();
                r.rem(jLabel5.getText(), jLabel4.getText(), jComboBox1.getSelectedItem().toString(), Double.parseDouble(jTextField1.getText()));
                JOptionPane.showMessageDialog( this, "Pago registrado");
                ResultSet rs = stmt.executeQuery("select max(idCompra) as maximo from compras");
                rs.next();
                String impresion = "C:\\Users\\NaMYY\\Desktop\\Farmacia\\Remisiones\\remision(" + rs.getString("maximo") + ").pdf";
                imprimir(impresion);
                stmt.close();
                cnn.close();
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actual.setVisible(false);
        anfitrion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        String selected = jComboBox1.getSelectedItem().toString();
        switch(selected){
            case "consulta":
                jTextField1.setText(consulta + "");
                break;
            case "vacunas":
                jTextField1.setText(vacunas + "");
                break;
            case "medicamentos":
                jTextField1.setText("0");
                break;
        }
    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        String selected = jComboBox1.getSelectedItem().toString();
        switch(selected){
            case "consulta":
                jTextField1.setText(consulta + "");
                break;
            case "vacunas":
                jTextField1.setText(vacunas + "");
                break;
            case "medicamentos":
                jTextField1.setText("0");
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    private void imprimir(String impresion){
        try{
            Thread.sleep(1000);
            remision.loadPDF(impresion);
            PrintSettings p = new PrintSettings();
            p.m_AutoRotate = true;
            p.m_CenterInPage = true;
            p.m_ExpandToMargins = true;
            p.m_PrintAnnotations = true;
            p.m_QoppaDialog = true;
            p.m_ShrinkToMargins = true;
            remision.print(p);
        } catch (PDFException | PrinterException | InterruptedException ex) {
            imprimir(impresion);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}